# Generated by Django 5.1.6 on 2025-03-01 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('acquisition_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('acquisition_probability', models.DecimalField(decimal_places=2, help_text='Probability in percentage', max_digits=5)),
                ('dos', models.DateField(verbose_name='Date of Start')),
                ('sop', models.DateField(verbose_name='Start of Production')),
                ('eop', models.DateField(verbose_name='End of Production')),
                ('responsible', models.CharField(help_text='Person responsible for the project', max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('products', models.ManyToManyField(blank=True, related_name='projects', to='core.product')),
            ],
        ),
    ]
