# Generated by Django 5.1.6 on 2025-03-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='schedule_years',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
