# Generated by Django 5.1.6 on 2025-03-15 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_schedule_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='product',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='product',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='product',
        ),
        migrations.AddField(
            model_name='cost',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='core.item'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='core.item'),
        ),
        migrations.AddField(
            model_name='volume',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='core.item'),
        ),
    ]
