# Generated by Django 5.1.6 on 2025-03-22 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_cost_base_cost_alter_cost_labor_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sold_to',
        ),
        migrations.AddField(
            model_name='item',
            name='sold_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costing', to='core.item'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume', to='core.item'),
        ),
    ]
