# Generated by Django 5.1.6 on 2025-03-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_location_address_userrequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='value',
        ),
        migrations.AddField(
            model_name='userrequest',
            name='data',
            field=models.JSONField(default=0),
        ),
    ]
