# Generated by Django 5.1.6 on 2025-03-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_userrequest_comment_remove_userrequest_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='data',
            field=models.JSONField(verbose_name={}),
        ),
    ]
