# Generated by Django 5.1.6 on 2025-03-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_userrequest_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='data',
            field=models.JSONField(),
        ),
    ]
