# Generated by Django 5.1.6 on 2025-03-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='acquisition_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, null=True),
        ),
    ]
