# Generated by Django 5.1.6 on 2025-03-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_project_acquisition_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='acquisition_probability',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
