# Generated by Django 5.1.6 on 2025-03-24 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_project_dos_alter_project_eop_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='acquisition_probability',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='acquisition_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='dos',
            field=models.DateField(verbose_name='Date of Start'),
        ),
        migrations.AlterField(
            model_name='project',
            name='eop',
            field=models.DateField(verbose_name='End of Production'),
        ),
        migrations.AlterField(
            model_name='project',
            name='responsible',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='sop',
            field=models.DateField(verbose_name='Start of Production'),
        ),
    ]
